language: node_js

node_js:
  - "9"

cache:
  directories:
    - ~/dist

jobs:
  include:
    - stage: build
      script: ./scripts/build.sh
    - stage: deploy-docs
      script: ./scripts/deploy-docs.sh
