language: node_js

node_js:
  - "9"

jobs:
  include:
    - stage: build
      script: ./scripts/build

deploy:
  provider: pages
  local-dir: ./docs/.vuepress/dist
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: master
