language: node_js

node_js:
  - "9"

cache:
  directories:
    - node_modules

script: ./scripts/build.sh

deploy:
  provider: pages
  local-dir: ./docs/.vuepress/dist
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: master
