language: node_js

node_js:
  - "9"

cache:
  directories:
    - node_modules

jobs:
  include:
    - stage: build
      script: ./scripts/build.sh
    - stage: deploy-docs
      deploy:
        provider: pages
        local-dir: ./docs/.vuepress/dist
        skip-cleanup: true
        github-token: $GITHUB_TOKEN
        keep-history: true
        on:
          branch: master
    - stage: release
      deploy:
        provider: script
        skip_cleanup: true
        script:
          - npm run semantic-release
        on:
          branch: master
